CREATE TABLE TODO (
    ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    SEQUENTIAL SERIAL,
    UPDATE_AT TIMESTAMP NOT NULL,
    COMPLETED BOOLEAN,
    DATE_COMPLETED TIMESTAMP,
    DESCRIPTION VARCHAR(255), TITLE VARCHAR(255),
    AUTH_USER UUID,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_TODO (
    TODO UUID NOT NULL,
    AUTH_USER UUID NOT NULL
);

ALTER TABLE TODO ADD CONSTRAINT FK_TODO__AUTH_USER FOREIGN KEY (AUTH_USER) REFERENCES AUTH_USER;

ALTER TABLE USER_TODO ADD CONSTRAINT FK_USER_TODO__AUTH_USER FOREIGN KEY (AUTH_USER) REFERENCES AUTH_USER;

ALTER TABLE USER_TODO ADD CONSTRAINT FK_USER_TODO__TODO FOREIGN KEY (TODO) REFERENCES TODO;