CREATE TABLE AUTH_USER (
    ID UUID NOT NULL UNIQUE,
    SEQUENTIAL SERIAL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATE_AT TIMESTAMP NOT NULL,
    USERNAME VARCHAR(10) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    ROLES VARCHAR(255),
    STATUS VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT (
    ID UUID NOT NULL UNIQUE,
    SEQUENTIAL SERIAL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATE_AT TIMESTAMP NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    STATUS VARCHAR(255) NOT NULL,
    AUTH_USER UUID NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_USER FOREIGN KEY (AUTH_USER) REFERENCES AUTH_USER
);

INSERT INTO AUTH_USER (ID, SEQUENTIAL, CREATED_AT, UPDATE_AT, NAME, USERNAME, PASSWORD, EMAIL, PHONE, STATUS, ROLES) VALUES ('afdce236-1f48-4a4d-ba2b-8669554caede', 1, '2020-05-29T23:43:00.114934', '2020-05-29T23:43:00.114976', 'Gabriel Longarete Mandelli', 'mandelli', '$2a$10$L9AzOpYyNdErdA38lZA6KOGpPSYXaqwI7bVGO7SpC9JOUl7xO5vN2', 'gabriel-mandelli@hotmail.com', '48999233069', 'ENABLED', 'ADMIN');
