CREATE TABLE AUTH_USER (ID UUID NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL UNIQUE,
    UPDATE_AT TIMESTAMP NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    ROLES VARCHAR(255),
    STATUS VARCHAR(255),
    USERNAME VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CLIENT (
    ID UUID NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATE_AT TIMESTAMP NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    STATUS VARCHAR(255),
    AUTH_USER UUID,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENT_USER FOREIGN KEY (AUTH_USER) REFERENCES AUTH_USER
);

INSERT INTO AUTH_USER (ID, CREATED_AT, UPDATE_AT, NAME, USERNAME, PASSWORD, EMAIL, PHONE, STATUS, ROLES) VALUES ('afdce236-1f48-4a4d-ba2b-8669554caede', '2020-05-29T23:43:00.114934', '2020-05-29T23:43:00.114976', 'Gabriel Longarete Mandelli', 'mandelli', '$2a$10$fIk80xiviSfSMWS8FhGxfeioniT6adCUDVFhCYZdJV6kVrzBmmLzK', 'gabriel-mandelli@hotmail.com', '48999233069', 'ENABLED', 'ADMIN');
